module.exports = {
  docs: [
    {
      type: 'category',
      label: '入门指南',
      collapsed: false,
      items: ['index', 'intro/environment', 'intro/cli', 'intro/cdn', 'intro/vscode-extension', 'intro/next'],
    },
    {
      type: 'category',
      label: '升级指南',
      collapsed: false,
      items: ['updating/8-0', 'updating/7-0', 'updating/6-0', 'updating/5-0', 'updating/4-0'],
    },
    {
      type: 'category',
      label: '开发',
      collapsed: false,
      items: [
        'developing/starting',
        'developing/previewing',
        'developing/scaffolding',
        'developing/ios',
        'developing/android',
        'developing/tips',
        'developing/hardware-back-button',
        'developing/keyboard',
        'developing/config',
        'developing/managing-focus',
      ],
    },
    {
      type: 'category',
      label: '布局',
      collapsed: false,
      items: [
        'layout/structure',
        {
          type: 'link',
          label: '响应式网格',
          href: '/docs/api/grid',
        },
        'layout/global-stylesheets',
        'layout/css-utilities',
        'layout/dynamic-font-scaling',
      ],
    },
    {
      type: 'category',
      label: '主题',
      collapsed: false,
      items: [
        'theming/basics',
        'theming/platform-styles',
        'theming/css-variables',
        'theming/css-shadow-parts',
        'theming/colors',
        'theming/themes',
        'theming/dark-mode',
        'theming/high-contrast-mode',
        'theming/advanced',
        'theming/color-generator',
      ],
    },
    {
      type: 'category',
      label: 'Angular',
      collapsed: false,
      items: [
        'angular/overview',
        'angular/quickstart',
        {
          type: 'category',
          label: '构建你的第一个应用',
          items: [
            'angular/your-first-app',
            'angular/your-first-app/taking-photos',
            'angular/your-first-app/saving-photos',
            'angular/your-first-app/loading-photos',
            'angular/your-first-app/adding-mobile',
            'angular/your-first-app/deploying-mobile',
            'angular/your-first-app/live-reload',
            'angular/your-first-app/distribute',
          ],
        },
        'angular/add-to-existing',
        'angular/build-options',
        'angular/lifecycle',
        'angular/navigation',
        'angular/overlays',
        'angular/injection-tokens',
        'angular/virtual-scroll',
        'angular/slides',
        'angular/platform',
        'angular/testing',
        'angular/storage',
        'angular/performance',
        'angular/pwa',
      ],
    },
    {
      type: 'category',
      label: 'JavaScript',
      collapsed: false,
      items: ['javascript/overview', 'javascript/quickstart'],
    },
    {
      type: 'category',
      label: 'React',
      collapsed: false,
      items: [
        'react/overview',
        'react/quickstart',
        {
          type: 'category',
          label: '构建你的第一个应用',
          items: [
            'react/your-first-app',
            'react/your-first-app/taking-photos',
            'react/your-first-app/saving-photos',
            'react/your-first-app/loading-photos',
            'react/your-first-app/adding-mobile',
            'react/your-first-app/deploying-mobile',
            'react/your-first-app/live-reload',
            'react/your-first-app/distribute',
          ],
        },
        'react/add-to-existing',
        'react/lifecycle',
        'react/navigation',
        'react/virtual-scroll',
        'react/slides',
        'react/platform',
        'react/pwa',
        'react/overlays',
        'react/storage',
        {
          type: 'category',
          label: '测试',
          items: [
            'react/testing/introduction',
            {
              type: 'category',
              label: '单元测试',
              collapsed: false,
              items: [
                'react/testing/unit-testing/setup',
                'react/testing/unit-testing/examples',
                'react/testing/unit-testing/best-practices',
              ],
            },
          ],
        },
        'react/performance',
      ],
    },
    {
      type: 'category',
      label: 'Vue',
      collapsed: false,
      items: [
        'vue/overview',
        'vue/quickstart',
        {
          type: 'category',
          label: '构建你的第一个应用',
          items: [
            'vue/your-first-app',
            'vue/your-first-app/taking-photos',
            'vue/your-first-app/saving-photos',
            'vue/your-first-app/loading-photos',
            'vue/your-first-app/adding-mobile',
            'vue/your-first-app/deploying-mobile',
            'vue/your-first-app/live-reload',
            'vue/your-first-app/distribute',
          ],
        },
        'vue/add-to-existing',
        'vue/build-options',
        'vue/lifecycle',
        'vue/navigation',
        'vue/virtual-scroll',
        'vue/slides',
        'vue/utility-functions',
        'vue/platform',
        'vue/pwa',
        'vue/storage',
        'vue/troubleshooting',
        'vue/performance',
      ],
    },
    {
      type: 'category',
      label: '实用工具',
      collapsed: false,
      items: ['utilities/animations', 'utilities/gestures'],
    },
    {
      type: 'category',
      label: '部署',
      collapsed: false,
      items: ['deployment/app-store', 'deployment/play-store', 'deployment/progressive-web-app'],
    },
    {
      type: 'category',
      label: '技术',
      collapsed: false,
      items: ['techniques/security'],
    },
    {
      type: 'category',
      label: '故障排除',
      collapsed: false,
      items: [
        'troubleshooting/debugging',
        'troubleshooting/build',
        'troubleshooting/runtime',
        'troubleshooting/native',
        'troubleshooting/cors',
      ],
    },
    {
      type: 'category',
      label: '核心概念',
      collapsed: false,
      items: [
        'core-concepts/fundamentals',
        'core-concepts/cross-platform',
        'core-concepts/webview',
        'core-concepts/what-are-progressive-web-apps',
      ],
    },
    {
      type: 'category',
      label: '贡献',
      collapsed: false,
      items: ['contributing/how-to-contribute', 'contributing/coc'],
    },
    {
      type: 'category',
      label: '参考',
      collapsed: false,
      items: [
        'reference/glossary',
        'reference/versioning',
        'reference/release-notes',
        {
          type: 'link',
          label: 'GitHub 更新日志',
          href: 'https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md',
        },
        'reference/support',
        'reference/browser-support',
      ],
    },
  ],

  api: [
    {
      type: 'category',
      label: '入门指南',
      collapsed: false,
      items: ['components'],
    },
    {
      type: 'category',
      label: '手风琴',
      collapsed: false,
      items: ['api/accordion', 'api/accordion-group'],
    },
    {
      type: 'category',
      label: '操作面板',
      collapsed: false,
      items: ['api/action-sheet'],
    },
    {
      type: 'category',
      label: '提示框',
      collapsed: false,
      items: ['api/alert'],
    },
    {
      type: 'category',
      label: '徽章',
      collapsed: false,
      items: ['api/badge'],
    },
    {
      type: 'category',
      label: '面包屑',
      collapsed: false,
      items: ['api/breadcrumb', 'api/breadcrumbs'],
    },
    {
      type: 'category',
      label: '按钮',
      collapsed: false,
      items: ['api/button', 'api/ripple-effect'],
    },
    {
      type: 'category',
      label: '卡片',
      collapsed: false,
      items: ['api/card', 'api/card-content', 'api/card-header', 'api/card-subtitle', 'api/card-title'],
    },
    {
      type: 'category',
      label: '复选框',
      collapsed: false,
      items: ['api/checkbox'],
    },
    {
      type: 'category',
      label: '纸片',
      collapsed: false,
      items: ['api/chip'],
    },
    {
      type: 'category',
      label: '内容',
      collapsed: false,
      items: ['api/app', 'api/content'],
    },
    {
      type: 'category',
      label: '日期和时间选择器',
      collapsed: false,
      items: [
        'api/datetime',
        'api/datetime-button',
        'api/picker',
        'api/picker-column',
        'api/picker-column-option',
        'api/picker-legacy',
      ],
    },
    {
      type: 'category',
      label: '浮动操作按钮',
      collapsed: false,
      items: ['api/fab', 'api/fab-button', 'api/fab-list'],
    },
    {
      type: 'category',
      label: '网格',
      collapsed: false,
      items: ['api/grid', 'api/col', 'api/row'],
    },
    {
      type: 'category',
      label: '图标',
      collapsed: false,
      items: ['api/icon'],
    },
    {
      type: 'category',
      label: '无限滚动',
      collapsed: false,
      items: ['api/infinite-scroll', 'api/infinite-scroll-content'],
    },
    {
      type: 'category',
      label: '输入',
      collapsed: false,
      items: ['api/input', 'api/input-password-toggle', 'api/input-otp', 'api/textarea'],
    },
    {
      type: 'category',
      label: '项目',
      collapsed: false,
      items: [
        'api/item',
        'api/item-divider',
        'api/item-group',
        'api/item-sliding',
        'api/item-options',
        'api/item-option',
        'api/label',
        'api/note',
      ],
    },
    {
      type: 'category',
      label: '列表',
      collapsed: false,
      items: ['api/list', 'api/list-header'],
    },
    {
      type: 'category',
      label: '媒体',
      collapsed: false,
      items: ['api/avatar', 'api/icon', 'api/img', 'api/thumbnail'],
    },
    {
      type: 'category',
      label: '菜单',
      collapsed: false,
      items: ['api/menu', 'api/menu-button', 'api/menu-toggle', 'api/split-pane'],
    },
    {
      type: 'category',
      label: '模态框',
      collapsed: false,
      items: ['api/modal', 'api/backdrop'],
    },
    {
      type: 'category',
      label: '导航',
      collapsed: false,
      items: ['api/nav', 'api/nav-link'],
    },
    {
      type: 'category',
      label: '弹出框',
      collapsed: false,
      items: ['api/popover'],
    },
    {
      type: 'category',
      label: '进度指示器',
      collapsed: false,
      items: ['api/loading', 'api/progress-bar', 'api/skeleton-text', 'api/spinner'],
    },
    {
      type: 'category',
      label: '单选按钮',
      collapsed: false,
      items: ['api/radio', 'api/radio-group'],
    },
    {
      type: 'category',
      label: '范围滑块',
      collapsed: false,
      items: ['api/range'],
    },
    {
      type: 'category',
      label: '刷新器',
      collapsed: false,
      items: ['api/refresher', 'api/refresher-content'],
    },
    {
      type: 'category',
      label: '重新排序',
      collapsed: false,
      items: ['api/reorder', 'api/reorder-group'],
    },
    {
      type: 'category',
      label: '路由',
      collapsed: false,
      items: ['api/router', 'api/router-link', 'api/router-outlet', 'api/route', 'api/route-redirect'],
    },
    {
      type: 'category',
      label: '搜索栏',
      collapsed: false,
      items: ['api/searchbar'],
    },
    {
      type: 'category',
      label: '分段',
      collapsed: false,
      items: ['api/segment', 'api/segment-button', 'api/segment-content', 'api/segment-view'],
    },
    {
      type: 'category',
      label: '选择框',
      collapsed: false,
      items: ['api/select', 'api/select-option'],
    },
    {
      type: 'category',
      label: '选项卡',
      collapsed: false,
      items: ['api/tabs', 'api/tab', 'api/tab-bar', 'api/tab-button'],
    },
    {
      type: 'category',
      label: '提示条',
      collapsed: false,
      items: ['api/toast'],
    },
    {
      type: 'category',
      label: '开关',
      collapsed: false,
      items: ['api/toggle'],
    },
    {
      type: 'category',
      label: '工具栏',
      collapsed: false,
      items: ['api/toolbar', 'api/header', 'api/footer', 'api/title', 'api/buttons', 'api/back-button'],
    },
    {
      type: 'category',
      label: '排版',
      collapsed: false,
      items: ['api/text'],
    },
    {
      type: 'category',
      label: '资源',
      collapsed: false,
      items: ['api'],
    },
  ],

  cli: [
    {
      type: 'category',
      label: 'CLI 文档',
      collapsed: false,
      items: [
        'cli',
        'cli/configuration',
        'cli/livereload',
        'cli/using-a-proxy',
        {
          type: 'link',
          label: '更新日志',
          href: 'https://github.com/ionic-team/ionic-cli/blob/develop/packages/@ionic/cli/CHANGELOG.md',
        },
      ],
    },
    {
      type: 'category',
      label: '命令参考',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'cli/commands', // 根据文件自动生成部分
        },
      ],
    },
  ],

  native: [
    {
      type: 'category',
      label: '入门指南',
      collapsed: false,
      items: ['native', 'native-setup', 'native-faq'],
    },
    {
      type: 'category',
      label: '插件',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'native', // 根据文件自动生成部分
        },
      ],
    },
  ],
};